apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgB6rDTPkXMrkcGv05T8xpH040gRmVhKQs6KNpxY5boRY/bDTyzzMiPvfJcDbhTUYdCjcBJ8ikr7l7snaFkQaJEHtKDq6euNP3pQNJFzSmg5FVI6Y795Wk3JMQEePUFQ8O28Ata00wNDrBzsNdKMVtXfSUofA+rD04w62MWUvE7gkSSeFLcxM/wuCtKdd5OOIkda4J0hMSqWysLji3BnfXIxgIFMcae0+8IuYhvl+/8/+1eJndzL+up3f5f+BZ9hYrUX2edGwgp5kKdBEylVc/V1+EmkoxK74n98goH0qpNCptCqbqx4c8wZq7R/Z6hWkhdrjZ+8KVUIbDxnM7H94+W71vAPnqMsfptp76y1saP5YvtBvP/j2LDstjPzUxHXsKegGXRu0JNw+2ch7HJt6BZr4rkfJVFR5FHgJ8pygPYsOkg8uEUmiYGcPMQ2sFu09Y9KavpZMbyhG1wNzmO1UPzhOK2WbsttmwN+9ZW8CmspRLXN7a4FRxDs/16yY7eyPns8jBjuOc9h1oNrCWgnd80KAxdKCXGb4y/S1GBQAdWVZBltjQE7+T/Lp8im06yQXYGcW+fuEWVW4qwtqxp9j/kVqHNJrD4tbId6Rn+Ff8yhiASWbPzJKbDFRsihn35K/hz6ikYZwVxwZk+NTaCe/PeyJ1zn92QfhupRKeRAMJ8AMCyQ1fHEK1eGEJ7WW8/M9mgFj0JPOeTtU5HVwjOorlr9x6s1QX2ZKXpku2x0vt2LGNjF9o+coBkC
    username: AgA6xfGNxNnZaR0k/R5trYj9y6ZmuhhlV7K4kKSGDhs5AULvaqgiSvZaizhK5Iv80TrXwJkIbX9TrwYlwId85Woncpbl0bGttbN7n/ONoqKK2EQTYGo7NxxqmBlFcWE1n2JNuDCmWwFkvRD0ff/Ml+aWp8XgyYT0rncKJGdHsS5gz/uMK3XLDwjocOq8aYMa0WME88mAYwL2493UbDJiyZHf3xDq0tOd/aQBxvIUc5+NGXVAd1NyoVbT2RfLXSJkBA6H3+5n2R6D0a6DvNYdg1nyAWaWFWNMVCLb2tOCjP0tBBDyqtH/04wCw/iW4uZaX12fcELHqy98btu3OiJM35knrajNLHT3LhZzF1ZWXo/f3KLmDNf763IJlQoS3acPL9Z8iPOwxvshH9A9hgGgBSBgKGlDKAz/Lrx5VfJoZ0LafTlgYLcv5Qz0uP+/sW7po0alcS7ilYY4IRZsotMYLMAnI5VPTJRaR9xbhKHDCh8n3FlG/1c1EbVQNpE9SXiKuc8/ZZz4QGEZwNityCfB6kh7R8/qEDvI+TIs7/qF+NUMptKRmMQfw9oMdLk/h83EJc12jQ27+TU3DJKhDGFJpP2BIqfz9nuERoHMonFaK1hc9ed60CKtdr8CI+45+sUXozfArg86cLGW9ssaSdNWkxD5jsaYafWTyy0hVX8bWeGCGjlPyznS76qNuySzCICyX1b8PGzq/A/BbTZS3Q==
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

