apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAtckriPDo2n3Qba3hrjfTvPI0DTe0eRTWugfflLQjgoji9PvN1imOg/nreP6fevFi5gWWfDNJAl1nidVhyG+wDzBa3pPLWMbMZ/t2Y6ZUIZpSJyMjHuDFSXKNzezGGeoupoTkaEmosCmm263wJJKyu2zNCL+NqHQnkacKCpy5d0ErBp/UfH+za88AEp0Y0gL8n1PPiAgPm4HegYafokKGbJGTTuj/USwD6T9YbIaUlknh5j3mdFuNn2HhkhhsFFvtmypnwrMMzmZfOAwAkCofyv5cS+mFtfY9jM3l4+J9Zb6EOHaMdfeAGX3gsVFJR/v+JGcXsm1ua3WHM0G0PElxqNn2CJrAleNpdCbrf4OjsgTJ4ImhYL1r8o/Ay5WvCxQZEljLqaWJPshNA1tEEsNRa1HuV48BBgdFPRjHkdZWoLKVbn98aGAeaKk5eEhvZ22g9BpuufIb8Qg3oWAYCjejYXwHSMsPOXdrnSvN2kmAwqqtoe4n6uPSdPmDpLXlXTmwAM93UczFgqK1bz0xDurt2nmLAcRpJxDSfQRCiMD014V2RO153ctES8VK8pXZdROKrolQT/IW+jc3LJFGhN/h2Nw+tvFM86ZNhjiB0aJMh+DDs4vR51HBum+3Dm966o7PSY2v3AD3IDeI7Phry2D4+tLmIUTlecIDj3cGhmO58zRSlzRbsCAuOewrYf+/LhAEiqHBrBr6PesIUP0ViQiBYQQ8MFot8kAe2qkfD5NZdH93xQJ9724av/Nnmgds9S+G3Nmxx+/8TWoQ491FAlfn8m5n98ktddCrnmPaShjk63CQdfKmYOt7ndWR8jwW47E/hA788Dzg8IIFQLTS2ZmVnuITW6SYlG/J9F9dSzj9XIjPMjSjzFVObP1pzrJhi5z7/BMZRfEqbPerzDXpbWUNa2Hpu+NEyOvXnB2GVK0qhhayBuhtKJHgRBz5UomYB7u8=
    IBM_ENTITLED_REGISTRY_USER: AgCIc7FxEVjc1JrAO0JpXqFQvIgNHuAGsFVyfpJfBggIpuPxDYEnu/QY9voQnjo3zc9GI1Zwz+qhgW5NwRnjwM7vZH+iUvMg3KhOcKP0T1rGdPnKpjjnwJFLQWfRygPcfKzwOwvymEk/KLc+r3TuXUy8zGMyIdDODbMp98XmyvU0UBpxp7Ha8iAz2aC5AXZqnlm6QbzpXzVCJv4ZbyfN0fGPfP2E48NjpMfYZ/0qB9FG2kI9AuC1IuT/4aBczxE8/ybKWP1M878tx6xCAWH6ugSZ6BVov3be0gfYNqD2Sfziy8Cf+rxjzMp/gucnEAPP9fciiwiy75brIXkdy4aR0qpZnz1Z0JSQEpZIJx7zMWjuSOUi7qWTOUEImFWlh91Gr40lIne5fSDWTtE/JQMCfgkeGV5+wAotCgfK9b2oWOC+0Brp5ldw8dO7n0BE/94VC+UQ+69Mvk/gbTgJJUK4TNi2GzN8mzbj3/w8C1vHv39z0yNMrsx7fHW0LkWA4COoss2BLXiFfC/+zQJG9SKY6m2OfQ4ZqwG+8h0TwWjILb90NX6dEQfsNz7HANi01JbVRh0YHW1z7QUFmt2f2vRWVFFOURv4uEADKkGV0SI9GFvBNpkdg6hdFP77wfSABM95BvhoktLL7yYW4GfB6T/2SC/v9EF9AYbLlKTGDPrFQRcjONcCn4bY8aKvIn4CQVALn8gFOg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

